### PR TITLE
Cfa

### PR DESCRIPTION
**Pull request by debuggingfuture**

### CODE REVIEW

**Comment by debuggingfuture** [comment]
@code4hk/bloggers

**Comment by amymok** [comment]
Typos:
著明 should be 著名
成積 should be 成績
Jennifer Pahlka was the Deputy CTO, not CTO
12 / 14 should be 12 / 17

You may want to talk about [FOIA](http://www.foia.gov), The Freedom of Information Act (FOIA) is a law that gives you the right to access information from the federal government. It is often described as the law that keeps citizens in the know about their government.  This Act enables government to open up their data.

**Comment by debuggingfuture** [comment]
@amymok added all thanks

**Comment by amymok** [comment]
Another comment, you have CODE4HK and Code4HK, be consistent

**Comment by amymok** [comment]
@vincentlaucy not every fellows are engineers, they are a variety of people that joined, such as designers, user researchers, policy analysts, people with GIS background, project managers.

**Comment by debuggingfuture** [comment]
@amymok added a bit for that but keep the subtitle

**Pull request merged**
